# Generated by Django 5.2.7 on 2025-11-02 11:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_limit_usd', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Monthly spending limit in USD (default: $5.00)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('daily_summary_limit', models.IntegerField(default=100, help_text='Daily summary generation limit (default: 100)', validators=[django.core.validators.MinValueValidator(0)])),
                ('ai_features_enabled', models.BooleanField(default=True, help_text='Emergency stop: disable all AI features when False')),
                ('default_model', models.CharField(default='gpt-4o-mini', help_text='Default OpenAI model for summary generation', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'settings',
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='has_summary',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('template_text', models.TextField(help_text='Template with variables like {content}, {title}, {author}')),
                ('category', models.CharField(choices=[('summarization', 'Summarization'), ('extraction', 'Extraction'), ('analysis', 'Analysis'), ('rating', 'Rating'), ('custom', 'Custom')], default='custom', max_length=50)),
                ('is_custom', models.BooleanField(default=False, help_text='True if created by user, False if built-in')),
                ('is_fabric', models.BooleanField(default=False, help_text='True if this is a Fabric prompt from GitHub')),
                ('variables_required', models.JSONField(default=list, help_text='List of required variables, e.g., ["content", "title"]')),
                ('default_model', models.CharField(default='gpt-4o-mini', help_text='Default OpenAI model to use', max_length=100)),
                ('version', models.CharField(default='1.0', help_text='Prompt version for tracking changes', max_length=20)),
                ('created_by', models.CharField(blank=True, help_text='User or system that created this prompt', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category'], name='books_core__categor_49d423_idx'), models.Index(fields=['is_fabric'], name='books_core__is_fabr_8eda11_idx'), models.Index(fields=['is_custom'], name='books_core__is_cust_0e45d9_idx')],
            },
        ),
        migrations.CreateModel(
            name='UsageTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date for daily tracking', unique=True)),
                ('month_year', models.CharField(db_index=True, help_text='Month in YYYY-MM format for monthly aggregation', max_length=7)),
                ('daily_summaries_count', models.IntegerField(default=0, help_text='Number of summaries generated today', validators=[django.core.validators.MinValueValidator(0)])),
                ('daily_tokens_used', models.IntegerField(default=0, help_text='Total tokens used today', validators=[django.core.validators.MinValueValidator(0)])),
                ('daily_cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), help_text='Total cost in USD for today', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('monthly_summaries_count', models.IntegerField(default=0, help_text='Number of summaries generated this month', validators=[django.core.validators.MinValueValidator(0)])),
                ('monthly_tokens_used', models.IntegerField(default=0, help_text='Total tokens used this month', validators=[django.core.validators.MinValueValidator(0)])),
                ('monthly_cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), help_text='Total cost in USD for this month', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='books_core__date_831fa8_idx'), models.Index(fields=['month_year'], name='books_core__month_y_946ea7_idx'), models.Index(fields=['-date'], name='books_core__date_294030_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('batch_summarization', 'Batch Summarization')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress_percent', models.IntegerField(default=0, help_text='Progress percentage (0-100)', validators=[django.core.validators.MinValueValidator(0)])),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict, help_text='Job-specific data including chapter_ids, prompt_id, per-chapter results')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='books_core.book')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['book', 'status'], name='books_core__book_id_3f08ec_idx'), models.Index(fields=['status'], name='books_core__status_64521f_idx'), models.Index(fields=['job_type'], name='books_core__job_typ_b1f89a_idx'), models.Index(fields=['-created_at'], name='books_core__created_bd2b40_idx')],
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_type', models.CharField(choices=[('tldr', 'TLDR'), ('key_points', 'Key Points'), ('analysis', 'Analysis'), ('custom', 'Custom')], default='tldr', max_length=50)),
                ('content_json', models.JSONField(default=dict, help_text='Summary content and metadata in JSON format')),
                ('tokens_used', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('model_used', models.CharField(help_text='OpenAI model used for generation', max_length=100)),
                ('processing_time_ms', models.IntegerField(default=0, help_text='Processing time in milliseconds', validators=[django.core.validators.MinValueValidator(0)])),
                ('version', models.IntegerField(default=1, help_text='Version number for tracking re-runs of same prompt', validators=[django.core.validators.MinValueValidator(1)])),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), help_text='Estimated cost in USD for generating this summary', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='books_core.chapter')),
                ('previous_version', models.ForeignKey(blank=True, help_text='Link to previous version of this summary', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='books_core.summary')),
                ('prompt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summaries', to='books_core.prompt')),
            ],
            options={
                'verbose_name_plural': 'summaries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['chapter'], name='books_core__chapter_663dbb_idx'), models.Index(fields=['prompt'], name='books_core__prompt__57ade4_idx'), models.Index(fields=['summary_type'], name='books_core__summary_8a3570_idx'), models.Index(fields=['-created_at'], name='books_core__created_24e96d_idx'), models.Index(fields=['chapter', 'prompt', 'version'], name='books_core__chapter_75f65e_idx')],
                'constraints': [models.UniqueConstraint(fields=('chapter', 'prompt', 'version'), name='unique_chapter_prompt_version')],
            },
        ),
    ]
