# Generated by Django 5.2.7 on 2025-11-04 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_core', '0002_settings_chapter_has_summary_prompt_usagetracking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='books_core.book'),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='job_type',
            field=models.CharField(choices=[('batch_summarization', 'Batch Summarization'), ('book_analysis', 'Book Analysis')], max_length=50),
        ),
        migrations.AlterField(
            model_name='summary',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='books_core.chapter'),
        ),
        migrations.AddIndex(
            model_name='summary',
            index=models.Index(fields=['book'], name='books_core__book_id_1fde3a_idx'),
        ),
        migrations.AddIndex(
            model_name='summary',
            index=models.Index(fields=['book', 'prompt', 'version'], name='books_core__book_id_8e7f3a_idx'),
        ),
        migrations.AddConstraint(
            model_name='summary',
            constraint=models.UniqueConstraint(fields=('book', 'prompt', 'version'), name='unique_book_prompt_version'),
        ),
        migrations.AddConstraint(
            model_name='summary',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('book__isnull', True), ('chapter__isnull', False)), models.Q(('book__isnull', False), ('chapter__isnull', True)), _connector='OR'), name='summary_chapter_or_book_not_both'),
        ),
    ]
