# Generated by Django 5.2.7 on 2026-01-11 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_core', '0005_add_pdf_support'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='book',
            new_name='books_core__file_ty_8c1c5e_idx',
            old_name='books_core__file_ty_1c5c9c_idx',
        ),
        migrations.RenameIndex(
            model_name='prompt',
            new_name='books_core__file_pa_616971_idx',
            old_name='books_core__file_pa_idx',
        ),
        migrations.AddField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('nonfiction', 'Non-Fiction'), ('fiction', 'Fiction')], db_index=True, default='nonfiction', help_text='Fiction or non-fiction classification', max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='source_file',
            field=models.FileField(upload_to='books/source/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='job_type',
            field=models.CharField(choices=[('batch_summarization', 'Batch Summarization'), ('book_analysis', 'Book Analysis'), ('chapter_analysis_pipeline', 'Chapter Analysis Pipeline')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['book_type'], name='books_core__book_ty_8cea65_idx'),
        ),
    ]
