# Generated by Django 5.2.7 on 2026-02-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_core', '0006_add_book_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='readability_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='chapter',
            name='readability_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
